### ISSUE TITLE
When marking a geokret, each section must be expanded. Previously, it was enough to scroll the page.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#891] opened 2023-11-08 08:20 UTC
![Снимок](https://github.com/geokrety/geokrety-website/assets/150231059/4d949a7e-dfc4-46f7-99d5-54fab291291c)

**Comment by okainov** [comment] 2023-11-08 12:37
Actually I have the same thing, while it might be useful for new users/guests to have wizard-like kind of process, for advanced users it just forces to do way more clicks, quite inconvenient...

**Comment by kumy** [comment] 2023-11-14 18:57
Duplicate of #722.
Closing here

**Closed by kumy** 2023-11-14 18:57 UTC

**Comment by SDymon** [comment] 2023-11-15 05:30
Disappointed in the impossibility of solving this problem!

**Comment by kumy** [comment] 2023-11-15 06:50
I can understand your frustration. But this form is quite complex, and require lot of care and unit testing to be robust. Thus a lot of time (and motivation) from my side, which I don't have at the moment. Sorry.

**Comment by SDymon** [comment] 2023-11-15 07:21
it's a pity.
