### ISSUE TITLE
Project infra scheme

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#376] opened 2019-06-04 21:58 UTC
Sorry for posting as an issue, but didn't really find any other way.

Just for my personal curiosity, do you have some kind of scheme/diagram of current GK website services? To be more precise, I'm especially interested how do you make staging environment per-branch basis (because I'd like to use similar approach for geocaching website): create subdomains (automatically?), run the stuff (just Docker? How do you make CI to actually deploy the stuff?), get the database (do you have some script dumping prod database and then restoring the dump for freshly created staging environment?).

Also I saw some "cdn"-related stuff - is it also some separated service running on the same server? Or do you actually use Amazon or similar stuff?

**Comment by kumy** [comment] 2019-06-04 22:11
Unfortunately documentation is still missing since #290.

Some statements:
* new `environments` are not created automatically
* all is deployed thanks to Ansible https://github.com/geokrety/geokrety-ansible
* `environments` are represented in Ansible as an entry in a dict https://github.com/geokrety/geokrety-ansible/blob/8fc16aabbf05e8b0f050b199d5ade54fdf1a1f21/defaults/main.yml#L90-L107
* Database are still copied over manually, but it's a one line command that can be launched as cron (basically `docker exec mysqlA mysqldump -u user... | docker exec -i mysqlB bash -c "mysql -u user db2"`)
* Docker images are built during Ansible role and pushed to hub.docker.com registry.
* cdn are static files, served from the same server using only nginx in docker, I plan to migrate to some object store (minio)

Workkflow:
* We use [webhook](https://github.com/adnanh/webhook) project to receive events from github hooks
* `webhook` launch a wrapper taking some github json values as input
* the wrapper launch Ansible role on the specific `environment`
* domain name entries need to be created separately right now

**Comment by kumy** [comment] 2019-06-08 20:04
Let me close this as it's not a bug. Feel free to continue discussion if needed.

**Closed by kumy** 2019-06-08 20:04 UTC
Labels: question
