### ISSUE TITLE
ErrorException - recent_moves.php in handleError

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#211] opened 2018-11-09 19:46 UTC
https://sentry.kumy.org/geokrety/geokrety-legacy/issues/75

mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given
recent_moves.php in handleError at line 102

**Comment by kumy** [comment] 2018-11-09 19:56
Beside the missing checks in the code for this, we have some problem with the number of opened connections, it's especially visible under heavy traffic. From what I already seen, we open many connections for just one page request, seems like "patchy" code evolution :/

**Comment by boly38** [comment] 2018-11-09 20:05
'many connections' need to have his own issue or is it directly related to this page ?
then we could try to study how to reproduce/analyse/fix it.

for this sentry issue scope, we need to handle case result is false and trace related mysq error

saw that this page is use for mailing ?
maybe mailing produces a lots of connection at cron time ?

> seems like "patchy" code evolution
not sure what you mean here ?

**Comment by kumy** [comment] 2018-11-09 20:15
mailing is spread over the day (24 batch per day), and there is a small delay between each mail, I doubt this is the root cause.

> seems like "patchy" code evolution
[French - sorry] Je voulais dire que le code a du evoluer a coup de rustines dans le temps, et qu'il y a du avoir differentes methodes de connexion a la base de donnees qui s'empillent. Je pense qu'a chaque script-executé/page-vue, il doit y avoir au moins 3 connexions ouvertes vers la base. De plus j'ai deja vu dans les logs qu'il y a des moments ou on se prend 50 requetes par secondes, ca doit etre a ses moments la que la base refuse les nouvelles connexions..

**Comment by boly38** [comment] 2018-11-10 13:36
as part of the welcome page, maybe we need to implement cache for this sub-section (as well as the others). Cache could be short like 5 minutes and will prevent overloading db to query the same data for each visite..

**Comment by kumy** [comment] 2019-05-21 22:05
`recent_moves.php` not used anymore in `new-them` branch. So only mails sent via cron **will** still use this part of code.

**Comment by kumy** [comment] 2023-01-03 19:35
`GKv1` -> closing

**Closed by kumy** 2023-01-03 19:35 UTC
Labels: sentry
