### ISSUE TITLE
Non-compact list of geokret movement history.

### ISSUE THREAD

**Issue by SDymon** [geokrety/geokrety-website#896] opened 2023-11-08 08:37 UTC
![Снимок_marked](https://github.com/geokrety/geokrety-website/assets/150231059/e4e8b187-aa27-437d-81d8-bbf42d85129c)

In the old version of the site, more marks were placed on the page.

**Comment by kumy** [comment] 2023-11-14 18:58
Caused by #897.
There seems to be a glitch with the Dropzone css...
Closing here

**Closed by kumy** 2023-11-14 18:58 UTC

**Comment by SDymon** [comment] 2023-11-15 05:39
Fine! But I think that for an even more compact appearance, it is advisable to place a number of buttons (edit, delete, add photo, add comment) on the same line with the comment text.
