### ISSUE TITLE
API for getting GK data for more than 10 days is missing?

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#386] opened 2019-06-09 07:27 UTC
I'd like to do one-time full resync with GC.su, but I don't see how can I get all the data from GK website.

> Note: export*.php has a limit of retrieved data set at 10 days (ie you can download data changed in the past 10 days only). This should be enough to sync local OC nodes or other databases. To get older data check: here.

"here" link doesn't really work, it points to https://cdn.geokrety.org/exports/ where there is nothing really...

**Comment by kumy** [comment] 2019-06-09 08:31
Duplicate of #317?

**Comment by kumy** [comment] 2019-06-09 08:33
There is another repo with all scripts. You'll find the script that synchronize from gc.su here https://github.com/geokrety/geokrety-scripts/tree/master/waypointy/ru

**Comment by okainov** [comment] 2019-06-09 08:34
If this is still the intended way to get old data (no new API, no new methods etc), then yes, you can close it as duplicate :)

>There is another repo with all scripts. You'll find the script that synchronize from gc.su here 

Thanks, I think you pointed me to this one already. But those are scripts for GC->GK sync, I was talking about GK->GS sync (to make full re-sync for our geocaching database)

**Comment by kumy** [comment] 2019-06-09 08:54
Ho yes the other side sync :+1:, I'll check in the evening

**Comment by kumy** [comment] 2019-06-09 09:53
Link to https://github.com/GeoKretyMap/gkm-api-php/issues/16 https://github.com/GeoKretyMap/gkm-api-php/issues/17

**Comment by kumy** [comment] 2020-12-11 22:05
> "here" link doesn't really work, it points to https://cdn.geokrety.org/exports/ where there is nothing really...

New url is https://api.geokretymap.org/basex/export/. Commit pushed, doc should be updated in some minutes.

I can't understand why I didn't fixed this sooner. Sorry for the delay.

**Closed by kumy** 2020-12-11 22:05 UTC
Labels: -easy-, _MEDIUM
